Fix migrations issues in GH actions

diff --git a/.github/workflows/playwright-e2e.yml b/.github/workflows/playwright-e2e.yml
--- a/.github/workflows/playwright-e2e.yml
+++ b/.github/workflows/playwright-e2e.yml
@@ -34,8 +34,15 @@ jobs:
 
       - name: Start Django server
         run: |
-            docker compose exec -T devweb bash -c "python manage.py loaddata fixtures/*.json"
-            docker compose exec -T devweb bash -c "nohup python manage.py runserver 0.0.0.0:8081 &"
+            docker compose exec -T devweb bash -c '
+              set -e  # Exit immediately if any command fails
+              python manage.py makemigrations --merge --noinput &&
+              python manage.py makemigrations feedjack &&
+              python manage.py makemigrations &&
+              python manage.py migrate &&
+              python manage.py loaddata fixtures/*.json
+              nohup python manage.py runserver 0.0.0.0:8081 &
+            '
             # Wait for the server to start
             until curl -s http://localhost:62202; do
               echo "Waiting for Django server to be up..."
